parameters:
  fos_message.message_meta_class: '%fos_message.message_class%Metadata'
  fos_message.thread_meta_class: '%fos_message.thread_class%Metadata'

services:
  fos_message.message_manager.default:
    class: FOS\MessageBundle\EntityManager\MessageManager
    public: false
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@fos_message.message.entity.factory'
      - '@fos_message.message_meta_data.entity.factory'

  fos_message.message.entity.factory:
    class: FOS\MessageBundle\Model\MessageFactory
    arguments:
      - '%fos_message.message_class%'

  fos_message.message_meta_data.entity.factory:
    class: FOS\MessageBundle\Model\MessageMetadataFactory
    arguments:
      - '%fos_message.message_meta_class%'

  fos_message.thread_manager.default:
    class: FOS\MessageBundle\EntityManager\ThreadManager
    public: false
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@fos_message.thread.entity.factory'
      - '@fos_message.thread_meta_data.entity.factory'
      - '@fos_message.message_manager'

  fos_message.thread.entity.factory:
    class: FOS\MessageBundle\Model\ThreadFactory
    arguments:
      - '%fos_message.thread_class%'

  fos_message.thread_meta_data.entity.factory:
    class: FOS\MessageBundle\Model\ThreadMetadataFactory
    arguments:
      - '%fos_message.thread_meta_class%'