parameters:
  fos_message.thread_meta_class: '%fos_message.thread_class%Metadata'

services:
  fos_message.message_manager.default:
    class: FOS\MessageBundle\EntityManager\MessageManager
    public: false
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%fos_message.message_class%''

  fos_message.thread_manager.default:
    class: FOS\MessageBundle\EntityManager\ThreadManager
    public: false
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%fos_message.thread_class%'
      - '%fos_message.thread_meta_class%'
      - '@fos_message.message_manager'
